### ISSUE TITLE
Could this be adapted to Llama2? Which part should be modified?

### ISSUE THREAD

**Issue by Labmem009** [cmnfriend/O-LoRA#2]
Great work! This repo is built based on the pretrained T5-large model, but I wonder if it could be adapted to Llama2? And which part of this project should be modified? Thanks a lot!

**Comment by Labmem009** [comment]
I noticed that in your paper you trained another version for Llama-7B, could you please release this version of O-LoRA? Or a version adapted to Llama2?

**Comment by Labmem009** [comment]
I noticed the llama branch, which part of this branch should be modified to be adapted to Llama2?

**Comment by cmnfriend** [comment]
Sorry for late response, Maho senpai. I've updated the code to support LLaMA. You can try it by moving your hf llama model to initial_model/llama and run scripts_llama/order_1. 
However, I cannot ensure the validity of this version because I have not debugged on it due to the limitation of computation resource (it requires A100 GPUs to run). But I can check the code on Thursday, and I will inform you as soon as possible when I run the code successfully. 🙏

**Comment by ShristiDasBiswas** [comment]
Hi, Could you please update the code for llama3 support?
